services:
  - type: web
    name: quantum-ai-backend-2
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    numInstances: 1